### ISSUE TITLE
Can't install on macos

### ISSUE THREAD

**Issue by dannyob** [arvyy/islisp-truffle#5]
I downloaded the macos image, but when I try to execute it, I get the error '"islisp-macos" can't be opened because Apple cannot check it for malicious software. This software needs to be updated. Contact the developer for more information.'

sha256 of the islisp-macos binary is 3853bdffce9a5fb85431e34e8aa655a3218d9c40ac799e8c4497ca7697078790 
MacOS is Sonoma 14.5

**Comment by shaunsmith** [comment]
You need to clear the quarantine bit from the islisp-macos executable.  For example:

`sudo xattr -r -d com.apple.quarantine islisp-macos`

**Comment by arvyy** [comment]
Seems a proper solution requires paying apple in perpetuity for a license. For foreseeable future running on macos will require workarounds like what shaunsmith suggested.
